version: 0.0
os: linux
files:
  - source: imagedefinitions.json
    destination: /opt/codedeploy-agent/deployment-root
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
