version: 0.0
os: linux

files:
  - source: imagedefinitions.json
    destination: /home/ec2-user/app   # safer destination

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
