spring:
  datasource:
    url: jdbc:mysql://dbserver-1-preprod.chabfd3vu34d.ap-south-1.rds.amazonaws.com:3306/userinfo_project?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

server:
  port: 8080

logging:
  level:
    com.project.userinfo: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} {%thread} %-5level %logger{36} - %msg%n"
